[package]
name = "google_oauth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oauth2 = "4.4.2"
reqwest = "0.11.20"
tokio = { version = "1.32.0", features = ["full"] }
url = "2.4.1"
